// Code generated by goyacc -v y.output -o parser.go -p mtail parser.y. DO NOT EDIT.

//line parser.y:5
/* #nosec G104 generated code, errors reported do not make sense */
package parser

import __yyfmt__ "fmt"

//line parser.y:6

import (
	"time"

	"github.com/golang/glog"
	"github.com/jaqx0r/mtail/internal/metrics"
	"github.com/jaqx0r/mtail/internal/runtime/compiler/ast"
	"github.com/jaqx0r/mtail/internal/runtime/compiler/position"
)

//line parser.y:19
type mtailSymType struct {
	yys         int
	intVal      int64
	floatVal    float64
	floats      []float64
	op          int
	text        string
	texts       []string
	flag        bool
	n           ast.Node
	kind        metrics.Kind
	duration    time.Duration
	logMappings []string
	logMapping  *ast.LogMapping // Add this field for *ast.LogMapping
}

const INVALID = 57346
const COUNTER = 57347
const GAUGE = 57348
const TIMER = 57349
const TEXT = 57350
const HISTOGRAM = 57351
const AFTER = 57352
const AS = 57353
const BY = 57354
const CONST = 57355
const HIDDEN = 57356
const DEF = 57357
const DEL = 57358
const NEXT = 57359
const OTHERWISE = 57360
const ELSE = 57361
const STOP = 57362
const BUCKETS = 57363
const LIMIT = 57364
const BUILTIN = 57365
const REGEX = 57366
const STRING = 57367
const CAPREF = 57368
const CAPREF_NAMED = 57369
const ID = 57370
const DECO = 57371
const INTLITERAL = 57372
const FLOATLITERAL = 57373
const DURATIONLITERAL = 57374
const INC = 57375
const DEC = 57376
const DIV = 57377
const MOD = 57378
const MUL = 57379
const MINUS = 57380
const PLUS = 57381
const POW = 57382
const SHL = 57383
const SHR = 57384
const LT = 57385
const GT = 57386
const LE = 57387
const GE = 57388
const EQ = 57389
const NE = 57390
const BITAND = 57391
const XOR = 57392
const BITOR = 57393
const NOT = 57394
const AND = 57395
const OR = 57396
const ADD_ASSIGN = 57397
const ASSIGN = 57398
const MATCH = 57399
const NOT_MATCH = 57400
const LCURLY = 57401
const RCURLY = 57402
const LPAREN = 57403
const RPAREN = 57404
const LSQUARE = 57405
const RSQUARE = 57406
const COMMA = 57407
const NL = 57408
const LOGMAPPING = 57409

var mtailToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"INVALID",
	"COUNTER",
	"GAUGE",
	"TIMER",
	"TEXT",
	"HISTOGRAM",
	"AFTER",
	"AS",
	"BY",
	"CONST",
	"HIDDEN",
	"DEF",
	"DEL",
	"NEXT",
	"OTHERWISE",
	"ELSE",
	"STOP",
	"BUCKETS",
	"LIMIT",
	"BUILTIN",
	"REGEX",
	"STRING",
	"CAPREF",
	"CAPREF_NAMED",
	"ID",
	"DECO",
	"INTLITERAL",
	"FLOATLITERAL",
	"DURATIONLITERAL",
	"INC",
	"DEC",
	"DIV",
	"MOD",
	"MUL",
	"MINUS",
	"PLUS",
	"POW",
	"SHL",
	"SHR",
	"LT",
	"GT",
	"LE",
	"GE",
	"EQ",
	"NE",
	"BITAND",
	"XOR",
	"BITOR",
	"NOT",
	"AND",
	"OR",
	"ADD_ASSIGN",
	"ASSIGN",
	"MATCH",
	"NOT_MATCH",
	"LCURLY",
	"RCURLY",
	"LPAREN",
	"RPAREN",
	"LSQUARE",
	"RSQUARE",
	"COMMA",
	"NL",
	"LOGMAPPING",
}

var mtailStatenames = [...]string{}

const mtailEofCode = 1
const mtailErrCode = 2
const mtailInitialStackSize = 16

//line parser.y:762

// tokenpos returns the position of the current token.
func tokenpos(mtaillex mtailLexer) position.Position {
	return mtaillex.(*parser).t.Pos
}

// markedpos returns the position recorded from the most recent mark_pos
// production.
func markedpos(mtaillex mtailLexer) position.Position {
	return mtaillex.(*parser).pos
}

// positionFromMark returns a position spanning from the last mark to the current position.
func positionFromMark(mtaillex mtailLexer) position.Position {
	tp := tokenpos(mtaillex)
	mp := markedpos(mtaillex)
	return *position.Merge(&mp, &tp)
}

//line yacctab:1
var mtailExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 1,
	5, 97,
	6, 97,
	7, 97,
	8, 97,
	9, 97,
	-2, 128,
	-1, 24,
	66, 28,
	-2, 72,
	-1, 112,
	5, 97,
	6, 97,
	7, 97,
	8, 97,
	9, 97,
	-2, 128,
}

const mtailPrivate = 57344

const mtailLast = 255

var mtailAct = [...]uint8{
	178, 92, 132, 30, 17, 95, 44, 46, 29, 50,
	43, 133, 31, 108, 22, 90, 42, 26, 24, 134,
	107, 32, 21, 47, 58, 28, 27, 38, 36, 37,
	45, 189, 40, 41, 110, 109, 188, 91, 131, 89,
	38, 36, 37, 45, 93, 40, 41, 38, 36, 37,
	45, 94, 40, 41, 33, 174, 169, 170, 170, 66,
	67, 91, 113, 39, 145, 114, 117, 33, 136, 51,
	80, 81, 72, 118, 78, 77, 39, 66, 67, 74,
	76, 75, 175, 39, 53, 2, 123, 97, 98, 124,
	101, 100, 54, 125, 126, 135, 54, 176, 127, 128,
	129, 70, 71, 130, 186, 104, 105, 103, 45, 141,
	106, 192, 191, 116, 17, 182, 135, 137, 29, 181,
	138, 143, 180, 139, 22, 140, 148, 141, 24, 142,
	91, 135, 21, 167, 91, 158, 162, 112, 161, 164,
	165, 91, 91, 91, 171, 173, 172, 168, 163, 166,
	160, 159, 49, 146, 14, 83, 84, 85, 86, 87,
	88, 147, 149, 12, 25, 185, 184, 11, 122, 53,
	13, 121, 135, 187, 14, 38, 36, 37, 45, 111,
	40, 41, 115, 12, 25, 70, 71, 11, 1, 190,
	13, 68, 48, 4, 183, 38, 36, 37, 45, 152,
	40, 41, 33, 69, 55, 57, 79, 52, 102, 99,
	144, 39, 53, 65, 73, 96, 18, 15, 56, 155,
	154, 82, 33, 20, 54, 177, 150, 179, 151, 156,
	157, 39, 153, 59, 35, 120, 18, 15, 60, 61,
	62, 63, 64, 10, 9, 8, 119, 7, 34, 23,
	19, 6, 16, 5, 3,
}

var mtailPact = [...]int16{
	-1000, -1000, 170, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 80, -1000, -1000, 127, 10, 189, -1000, -42,
	233, 24, 24, -1000, 68, -1000, 33, 30, -1000, 19,
	13, -1000, 112, 15, -19, -1000, -1000, -1000, -1000, 15,
	-1000, -1000, 46, -1000, 52, -1000, 70, -53, -31, -1000,
	160, -1000, 10, 4, -1000, 85, 10, 22, -1000, 143,
	-1000, -1000, -1000, -1000, -1000, -53, -1000, -1000, -53, -1000,
	-1000, -1000, -53, -53, -1000, -1000, -1000, -53, -53, -53,
	-1000, -1000, -53, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	68, -1000, 146, 15, 6, -1000, -53, -1000, -1000, -53,
	-1000, -1000, -53, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	104, 10, 150, -1000, 2, 137, 10, -1000, 152, 208,
	-1000, -1000, -1000, 15, 15, 80, 15, 15, 15, 22,
	15, -8, -1000, 24, -1000, 61, -1000, 15, 15, 15,
	33, 57, -1000, -1000, -1000, -1000, -7, 47, -1000, 65,
	-1000, -1000, -1000, -1000, 94, 90, 135, 74, 24, 30,
	-1000, -1000, -1000, 112, 24, 24, -1000, -1000, 46, -1000,
	15, 52, 70, -1000, -1000, -1000, -1000, -29, -1000, -1000,
	-1000, -1000, -1000, -34, -1000, -1000, -1000, -1000, 94, 81,
	-1000, -1000, -1000,
}

var mtailPgo = [...]uint8{
	0, 85, 254, 38, 9, 253, 252, 251, 250, 3,
	7, 6, 15, 5, 249, 21, 16, 26, 11, 248,
	10, 17, 19, 247, 246, 245, 244, 12, 25, 243,
	235, 234, 2, 233, 232, 228, 227, 0, 226, 225,
	223, 221, 215, 214, 191, 209, 208, 206, 203, 199,
	194, 193, 192, 188, 20, 1, 182,
}

var mtailR1 = [...]int8{
	0, 53, 1, 1, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 51, 52, 52, 5, 5,
	5, 6, 6, 6, 7, 7, 4, 8, 8, 14,
	14, 18, 18, 18, 18, 44, 44, 17, 17, 43,
	43, 43, 15, 15, 41, 41, 41, 41, 41, 41,
	16, 16, 42, 42, 11, 11, 45, 45, 28, 28,
	47, 47, 22, 21, 21, 21, 10, 10, 46, 46,
	46, 46, 13, 13, 12, 12, 48, 48, 9, 9,
	9, 9, 9, 9, 9, 9, 19, 19, 20, 31,
	31, 3, 3, 32, 32, 27, 23, 40, 40, 24,
	24, 24, 24, 24, 30, 30, 33, 33, 33, 33,
	33, 38, 39, 39, 37, 35, 34, 49, 50, 50,
	50, 50, 25, 26, 29, 29, 36, 36, 55, 56,
	54, 54,
}

var mtailR2 = [...]int8{
	0, 1, 0, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 4, 1, 1, 3, 1, 3, 4, 2,
	3, 1, 4, 1, 1, 2, 3, 1, 1, 4,
	4, 1, 1, 4, 4, 1, 1, 1, 4, 1,
	1, 1, 1, 4, 1, 1, 1, 1, 1, 1,
	1, 4, 1, 1, 1, 4, 1, 1, 4, 4,
	1, 1, 1, 1, 4, 4, 1, 4, 1, 1,
	1, 1, 1, 2, 1, 2, 1, 1, 1, 1,
	1, 1, 1, 3, 1, 1, 1, 4, 1, 4,
	5, 1, 3, 1, 1, 5, 3, 0, 1, 2,
	2, 2, 2, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 1, 3, 1, 2, 2, 2, 1, 1,
	3, 3, 4, 3, 5, 3, 1, 1, 0, 0,
	0, 1,
}

var mtailChk = [...]int16{
	-1000, -53, -1, -2, -51, -5, -7, -23, -25, -26,
	-29, 17, 13, 20, 4, 67, -6, -55, 66, -8,
	-40, -22, -18, -14, -12, 14, -21, -17, -28, -13,
	-9, -27, -15, 52, -19, -31, 26, 27, 25, 61,
	30, 31, -16, -20, -11, 28, -10, -20, -52, 25,
	-4, 59, 18, 23, 35, 15, 29, 16, 66, -33,
	5, 6, 7, 8, 9, -44, 53, 54, -44, -48,
	33, 34, 39, -43, 49, 51, 50, 56, 55, -47,
	57, 58, -41, 43, 44, 45, 46, 47, 48, -13,
	-12, -9, -55, 63, -18, -13, -42, 41, 42, -45,
	39, 38, -46, 37, 35, 36, 40, -54, 66, 66,
	65, 19, -1, -4, 61, -56, 28, -4, -12, -24,
	-30, 28, 25, -54, -54, -54, -54, -54, -54, -54,
	-54, -3, -32, -18, -22, -55, 62, -54, -54, -54,
	-21, -55, 25, -4, 60, 62, -3, 24, -4, 10,
	-38, -35, -49, -34, 12, 11, 21, 22, -18, -17,
	-28, -27, -20, -15, -18, -18, -22, -9, -16, 64,
	65, -11, -10, -13, 62, 35, 32, -39, -37, -36,
	28, 25, 25, -50, 31, 30, 30, -32, 65, 65,
	-37, 31, 30,
}

var mtailDef = [...]int16{
	2, -2, -2, 3, 4, 5, 6, 7, 8, 9,
	10, 11, 0, 13, 14, 0, 0, 0, 24, 0,
	0, 21, 23, 27, -2, 98, 62, 31, 32, 66,
	74, 63, 37, 128, 78, 79, 80, 81, 82, 128,
	84, 85, 42, 86, 50, 88, 54, 130, 0, 16,
	19, 2, 0, 0, 129, 0, 0, 128, 25, 0,
	106, 107, 108, 109, 110, 130, 35, 36, 130, 75,
	76, 77, 130, 130, 39, 40, 41, 130, 130, 130,
	60, 61, 130, 44, 45, 46, 47, 48, 49, 73,
	72, 74, 0, 128, 0, 66, 130, 52, 53, 130,
	56, 57, 130, 68, 69, 70, 71, 128, 131, 15,
	0, 0, -2, 20, 128, 0, 0, 123, 125, 96,
	103, 104, 105, 128, 128, 128, 128, 128, 128, 128,
	128, 0, 91, 93, 94, 0, 83, 128, 128, 128,
	12, 0, 17, 18, 26, 89, 0, 0, 122, 0,
	99, 100, 101, 102, 0, 0, 0, 0, 22, 33,
	34, 64, 65, 38, 29, 30, 58, 59, 43, 87,
	128, 51, 55, 67, 90, 95, 124, 111, 112, 114,
	126, 127, 115, 117, 118, 119, 116, 92, 0, 0,
	113, 120, 121,
}

var mtailTok1 = [...]int8{
	1,
}

var mtailTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67,
}

var mtailTok3 = [...]int8{
	0,
}

var mtailErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{
	{115, 4, "unexpected end of file, expecting '/' to end regex"},
	{17, 1, "unexpected end of file, expecting '}' to end block"},
	{17, 1, "unexpected end of file, expecting '}' to end block"},
	{17, 1, "unexpected end of file, expecting '}' to end block"},
	{16, 63, "unexpected indexing of an expression"},
	{16, 66, "statement with no effect, missing an assignment, `+' concatenation, or `{}' block?"},
}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	mtailDebug        = 0
	mtailErrorVerbose = false
)

type mtailLexer interface {
	Lex(lval *mtailSymType) int
	Error(s string)
}

type mtailParser interface {
	Parse(mtailLexer) int
	Lookahead() int
}

type mtailParserImpl struct {
	lval  mtailSymType
	stack [mtailInitialStackSize]mtailSymType
	char  int
}

func (p *mtailParserImpl) Lookahead() int {
	return p.char
}

func mtailNewParser() mtailParser {
	return &mtailParserImpl{}
}

const mtailFlag = -1000

func mtailTokname(c int) string {
	if c >= 1 && c-1 < len(mtailToknames) {
		if mtailToknames[c-1] != "" {
			return mtailToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func mtailStatname(s int) string {
	if s >= 0 && s < len(mtailStatenames) {
		if mtailStatenames[s] != "" {
			return mtailStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func mtailErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !mtailErrorVerbose {
		return "syntax error"
	}

	for _, e := range mtailErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + mtailTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(mtailPact[state])
	for tok := TOKSTART; tok-1 < len(mtailToknames); tok++ {
		if n := base + tok; n >= 0 && n < mtailLast && int(mtailChk[int(mtailAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if mtailDef[state] == -2 {
		i := 0
		for mtailExca[i] != -1 || int(mtailExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; mtailExca[i] >= 0; i += 2 {
			tok := int(mtailExca[i])
			if tok < TOKSTART || mtailExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if mtailExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += mtailTokname(tok)
	}
	return res
}

func mtaillex1(lex mtailLexer, lval *mtailSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(mtailTok1[0])
		goto out
	}
	if char < len(mtailTok1) {
		token = int(mtailTok1[char])
		goto out
	}
	if char >= mtailPrivate {
		if char < mtailPrivate+len(mtailTok2) {
			token = int(mtailTok2[char-mtailPrivate])
			goto out
		}
	}
	for i := 0; i < len(mtailTok3); i += 2 {
		token = int(mtailTok3[i+0])
		if token == char {
			token = int(mtailTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(mtailTok2[1]) /* unknown char */
	}
	if mtailDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", mtailTokname(token), uint(char))
	}
	return char, token
}

func mtailParse(mtaillex mtailLexer) int {
	return mtailNewParser().Parse(mtaillex)
}

func (mtailrcvr *mtailParserImpl) Parse(mtaillex mtailLexer) int {
	var mtailn int
	var mtailVAL mtailSymType
	var mtailDollar []mtailSymType
	_ = mtailDollar // silence set and not used
	mtailS := mtailrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	mtailstate := 0
	mtailrcvr.char = -1
	mtailtoken := -1 // mtailrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		mtailstate = -1
		mtailrcvr.char = -1
		mtailtoken = -1
	}()
	mtailp := -1
	goto mtailstack

ret0:
	return 0

ret1:
	return 1

mtailstack:
	/* put a state and value onto the stack */
	if mtailDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", mtailTokname(mtailtoken), mtailStatname(mtailstate))
	}

	mtailp++
	if mtailp >= len(mtailS) {
		nyys := make([]mtailSymType, len(mtailS)*2)
		copy(nyys, mtailS)
		mtailS = nyys
	}
	mtailS[mtailp] = mtailVAL
	mtailS[mtailp].yys = mtailstate

mtailnewstate:
	mtailn = int(mtailPact[mtailstate])
	if mtailn <= mtailFlag {
		goto mtaildefault /* simple state */
	}
	if mtailrcvr.char < 0 {
		mtailrcvr.char, mtailtoken = mtaillex1(mtaillex, &mtailrcvr.lval)
	}
	mtailn += mtailtoken
	if mtailn < 0 || mtailn >= mtailLast {
		goto mtaildefault
	}
	mtailn = int(mtailAct[mtailn])
	if int(mtailChk[mtailn]) == mtailtoken { /* valid shift */
		mtailrcvr.char = -1
		mtailtoken = -1
		mtailVAL = mtailrcvr.lval
		mtailstate = mtailn
		if Errflag > 0 {
			Errflag--
		}
		goto mtailstack
	}

mtaildefault:
	/* default state action */
	mtailn = int(mtailDef[mtailstate])
	if mtailn == -2 {
		if mtailrcvr.char < 0 {
			mtailrcvr.char, mtailtoken = mtaillex1(mtaillex, &mtailrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if mtailExca[xi+0] == -1 && int(mtailExca[xi+1]) == mtailstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			mtailn = int(mtailExca[xi+0])
			if mtailn < 0 || mtailn == mtailtoken {
				break
			}
		}
		mtailn = int(mtailExca[xi+1])
		if mtailn < 0 {
			goto ret0
		}
	}
	if mtailn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			mtaillex.Error(mtailErrorMessage(mtailstate, mtailtoken))
			Nerrs++
			if mtailDebug >= 1 {
				__yyfmt__.Printf("%s", mtailStatname(mtailstate))
				__yyfmt__.Printf(" saw %s\n", mtailTokname(mtailtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for mtailp >= 0 {
				mtailn = int(mtailPact[mtailS[mtailp].yys]) + mtailErrCode
				if mtailn >= 0 && mtailn < mtailLast {
					mtailstate = int(mtailAct[mtailn]) /* simulate a shift of "error" */
					if int(mtailChk[mtailstate]) == mtailErrCode {
						goto mtailstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if mtailDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", mtailS[mtailp].yys)
				}
				mtailp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if mtailDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", mtailTokname(mtailtoken))
			}
			if mtailtoken == mtailEofCode {
				goto ret1
			}
			mtailrcvr.char = -1
			mtailtoken = -1
			goto mtailnewstate /* try again in the same state */
		}
	}

	/* reduction by production mtailn */
	if mtailDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", mtailn, mtailStatname(mtailstate))
	}

	mtailnt := mtailn
	mtailpt := mtailp
	_ = mtailpt // guard against "declared and not used"

	mtailp -= int(mtailR2[mtailn])
	// mtailp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if mtailp+1 >= len(mtailS) {
		nyys := make([]mtailSymType, len(mtailS)*2)
		copy(nyys, mtailS)
		mtailS = nyys
	}
	mtailVAL = mtailS[mtailp+1]

	/* consult goto table to find next state */
	mtailn = int(mtailR1[mtailn])
	mtailg := int(mtailPgo[mtailn])
	mtailj := mtailg + mtailS[mtailp].yys + 1

	if mtailj >= mtailLast {
		mtailstate = int(mtailAct[mtailg])
	} else {
		mtailstate = int(mtailAct[mtailj])
		if int(mtailChk[mtailstate]) != -mtailn {
			mtailstate = int(mtailAct[mtailg])
		}
	}
	// dummy call; replaced with literal code
	switch mtailnt {

	case 1:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:99
		{
			mtaillex.(*parser).root = mtailDollar[1].n
		}
	case 2:
		mtailDollar = mtailS[mtailpt-0 : mtailpt+1]
//line parser.y:107
		{
			mtailVAL.n = &ast.StmtList{}
		}
	case 3:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:111
		{
			mtailVAL.n = mtailDollar[1].n
			if mtailDollar[2].n != nil {
				mtailVAL.n.(*ast.StmtList).Children = append(mtailVAL.n.(*ast.StmtList).Children, mtailDollar[2].n)
			}
		}
	case 4:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:122
		{
			mtailVAL.n = mtailDollar[1].logMapping
		}
	case 5:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:124
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 6:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:126
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 7:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:128
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 8:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:130
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 9:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:132
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 10:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:134
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 11:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:136
		{
			mtailVAL.n = &ast.NextStmt{tokenpos(mtaillex)}
		}
	case 12:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:140
		{
			mtailVAL.n = &ast.PatternFragment{ID: mtailDollar[2].n, Expr: mtailDollar[4].n}
		}
	case 13:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:144
		{
			mtailVAL.n = &ast.StopStmt{tokenpos(mtaillex)}
		}
	case 14:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:148
		{
			mtailVAL.n = &ast.Error{tokenpos(mtaillex), mtailDollar[1].text}
		}
	case 15:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:155
		{
			mtailVAL.logMapping = &ast.LogMapping{
				P:        tokenpos(mtaillex),
				Mappings: mtailDollar[2].logMappings, // $2 is the list of strings (type []string)
			}
		}
	case 16:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:165
		{
			mtailVAL.logMappings = []string{mtailDollar[1].text}
		}
	case 17:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:169
		{
			mtailVAL.logMappings = append(mtailDollar[1].logMappings, mtailDollar[3].text)
		}
	case 18:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:177
		{
			mtailVAL.n = &ast.CondStmt{mtailDollar[1].n, mtailDollar[2].n, mtailDollar[4].n, nil}
		}
	case 19:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:181
		{
			if mtailDollar[1].n != nil {
				mtailVAL.n = &ast.CondStmt{mtailDollar[1].n, mtailDollar[2].n, nil, nil}
			} else {
				mtailVAL.n = mtailDollar[2].n
			}
		}
	case 20:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:189
		{
			o := &ast.OtherwiseStmt{positionFromMark(mtaillex)}
			mtailVAL.n = &ast.CondStmt{o, mtailDollar[3].n, nil, nil}
		}
	case 21:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:197
		{
			mtailVAL.n = &ast.UnaryExpr{P: tokenpos(mtaillex), Expr: mtailDollar[1].n, Op: MATCH}
		}
	case 22:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:201
		{
			mtailVAL.n = &ast.BinaryExpr{
				LHS: &ast.UnaryExpr{P: tokenpos(mtaillex), Expr: mtailDollar[1].n, Op: MATCH},
				RHS: mtailDollar[4].n,
				Op:  mtailDollar[2].op,
			}
		}
	case 23:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:209
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 24:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:215
		{
			mtailVAL.n = nil
		}
	case 25:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:217
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 26:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:223
		{
			mtailVAL.n = mtailDollar[2].n
		}
	case 27:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:231
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 28:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:233
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 29:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:239
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 30:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:243
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 31:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:251
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 32:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:253
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 33:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:255
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 34:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:259
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 35:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:266
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 36:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:268
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 37:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:274
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 38:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:276
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 39:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:283
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 40:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:285
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 41:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:287
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 42:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:293
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 43:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:295
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 44:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:302
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 45:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:304
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 46:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:306
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 47:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:308
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 48:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:310
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 49:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:312
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 50:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:318
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 51:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:320
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 52:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:327
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 53:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:329
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 54:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:335
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 55:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:337
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 56:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:344
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 57:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:346
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 58:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:352
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 59:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:356
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 60:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:363
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 61:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:365
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 62:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:372
		{
			mtailVAL.n = &ast.PatternExpr{Expr: mtailDollar[1].n}
		}
	case 63:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:380
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 64:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:382
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: PLUS}
		}
	case 65:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:386
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: PLUS}
		}
	case 66:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:394
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 67:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:396
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 68:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:403
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 69:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:405
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 70:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:407
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 71:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:409
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 72:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:415
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 73:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:417
		{
			mtailVAL.n = &ast.UnaryExpr{P: tokenpos(mtaillex), Expr: mtailDollar[2].n, Op: mtailDollar[1].op}
		}
	case 74:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:425
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 75:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:427
		{
			mtailVAL.n = &ast.UnaryExpr{P: tokenpos(mtaillex), Expr: mtailDollar[1].n, Op: mtailDollar[2].op}
		}
	case 76:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:434
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 77:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:436
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 78:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:442
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 79:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:444
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 80:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:446
		{
			mtailVAL.n = &ast.CaprefTerm{tokenpos(mtaillex), mtailDollar[1].text, false, nil}
		}
	case 81:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:450
		{
			mtailVAL.n = &ast.CaprefTerm{tokenpos(mtaillex), mtailDollar[1].text, true, nil}
		}
	case 82:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:454
		{
			mtailVAL.n = &ast.StringLit{tokenpos(mtaillex), mtailDollar[1].text}
		}
	case 83:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:458
		{
			mtailVAL.n = mtailDollar[2].n
		}
	case 84:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:462
		{
			mtailVAL.n = &ast.IntLit{tokenpos(mtaillex), mtailDollar[1].intVal}
		}
	case 85:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:466
		{
			mtailVAL.n = &ast.FloatLit{tokenpos(mtaillex), mtailDollar[1].floatVal}
		}
	case 86:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:474
		{
			// Build an empty IndexedExpr so that the recursive rule below doesn't need to handle the alternative.
			mtailVAL.n = &ast.IndexedExpr{LHS: mtailDollar[1].n, Index: &ast.ExprList{}}
		}
	case 87:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:479
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.IndexedExpr).Index.(*ast.ExprList).Children = append(
				mtailVAL.n.(*ast.IndexedExpr).Index.(*ast.ExprList).Children,
				mtailDollar[3].n.(*ast.ExprList).Children...)
		}
	case 88:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:490
		{
			mtailVAL.n = &ast.IDTerm{tokenpos(mtaillex), mtailDollar[1].text, nil, false}
		}
	case 89:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:498
		{
			mtailVAL.n = &ast.BuiltinExpr{P: positionFromMark(mtaillex), Name: mtailDollar[2].text, Args: nil}
		}
	case 90:
		mtailDollar = mtailS[mtailpt-5 : mtailpt+1]
//line parser.y:502
		{
			mtailVAL.n = &ast.BuiltinExpr{P: positionFromMark(mtaillex), Name: mtailDollar[2].text, Args: mtailDollar[4].n}
		}
	case 91:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:511
		{
			mtailVAL.n = &ast.ExprList{}
			mtailVAL.n.(*ast.ExprList).Children = append(mtailVAL.n.(*ast.ExprList).Children, mtailDollar[1].n)
		}
	case 92:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:516
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.ExprList).Children = append(mtailVAL.n.(*ast.ExprList).Children, mtailDollar[3].n)
		}
	case 93:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:524
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 94:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:526
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 95:
		mtailDollar = mtailS[mtailpt-5 : mtailpt+1]
//line parser.y:532
		{
			mtailVAL.n = &ast.PatternLit{P: positionFromMark(mtaillex), Pattern: mtailDollar[4].text}
		}
	case 96:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:540
		{
			mtailVAL.n = mtailDollar[3].n
			d := mtailVAL.n.(*ast.VarDecl)
			d.Kind = mtailDollar[2].kind
			d.Hidden = mtailDollar[1].flag
		}
	case 97:
		mtailDollar = mtailS[mtailpt-0 : mtailpt+1]
//line parser.y:551
		{
			mtailVAL.flag = false
		}
	case 98:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:555
		{
			mtailVAL.flag = true
		}
	case 99:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:563
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.VarDecl).Keys = mtailDollar[2].texts
		}
	case 100:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:568
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.VarDecl).ExportedName = mtailDollar[2].text
		}
	case 101:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:573
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.VarDecl).Buckets = mtailDollar[2].floats
		}
	case 102:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:578
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.VarDecl).Limit = mtailDollar[2].intVal
		}
	case 103:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:583
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 104:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:591
		{
			mtailVAL.n = &ast.VarDecl{P: tokenpos(mtaillex), Name: mtailDollar[1].text}
		}
	case 105:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:595
		{
			mtailVAL.n = &ast.VarDecl{P: tokenpos(mtaillex), Name: mtailDollar[1].text}
		}
	case 106:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:603
		{
			mtailVAL.kind = metrics.Counter
		}
	case 107:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:607
		{
			mtailVAL.kind = metrics.Gauge
		}
	case 108:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:611
		{
			mtailVAL.kind = metrics.Timer
		}
	case 109:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:615
		{
			mtailVAL.kind = metrics.Text
		}
	case 110:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:619
		{
			mtailVAL.kind = metrics.Histogram
		}
	case 111:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:627
		{
			mtailVAL.texts = mtailDollar[2].texts
		}
	case 112:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:634
		{
			mtailVAL.texts = make([]string, 0)
			mtailVAL.texts = append(mtailVAL.texts, mtailDollar[1].text)
		}
	case 113:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:639
		{
			mtailVAL.texts = mtailDollar[1].texts
			mtailVAL.texts = append(mtailVAL.texts, mtailDollar[3].text)
		}
	case 114:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:647
		{
			mtailVAL.text = mtailDollar[1].text
		}
	case 115:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:653
		{
			mtailVAL.text = mtailDollar[2].text
		}
	case 116:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:660
		{
			mtailVAL.intVal = mtailDollar[2].intVal
		}
	case 117:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:668
		{
			mtailVAL.floats = mtailDollar[2].floats
		}
	case 118:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:674
		{
			mtailVAL.floats = make([]float64, 0)
			mtailVAL.floats = append(mtailVAL.floats, mtailDollar[1].floatVal)
		}
	case 119:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:679
		{
			mtailVAL.floats = make([]float64, 0)
			mtailVAL.floats = append(mtailVAL.floats, float64(mtailDollar[1].intVal))
		}
	case 120:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:684
		{
			mtailVAL.floats = mtailDollar[1].floats
			mtailVAL.floats = append(mtailVAL.floats, mtailDollar[3].floatVal)
		}
	case 121:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:689
		{
			mtailVAL.floats = mtailDollar[1].floats
			mtailVAL.floats = append(mtailVAL.floats, float64(mtailDollar[3].intVal))
		}
	case 122:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:697
		{
			mtailVAL.n = &ast.DecoDecl{P: markedpos(mtaillex), Name: mtailDollar[3].text, Block: mtailDollar[4].n}
		}
	case 123:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:705
		{
			mtailVAL.n = &ast.DecoStmt{markedpos(mtaillex), mtailDollar[2].text, mtailDollar[3].n, nil, nil}
		}
	case 124:
		mtailDollar = mtailS[mtailpt-5 : mtailpt+1]
//line parser.y:713
		{
			mtailVAL.n = &ast.DelStmt{P: positionFromMark(mtaillex), N: mtailDollar[3].n, Expiry: mtailDollar[5].duration}
		}
	case 125:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:717
		{
			mtailVAL.n = &ast.DelStmt{P: positionFromMark(mtaillex), N: mtailDollar[3].n}
		}
	case 126:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:724
		{
			mtailVAL.text = mtailDollar[1].text
		}
	case 127:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:728
		{
			mtailVAL.text = mtailDollar[1].text
		}
	case 128:
		mtailDollar = mtailS[mtailpt-0 : mtailpt+1]
//line parser.y:738
		{
			glog.V(2).Infof("position marked at %v", tokenpos(mtaillex))
			mtaillex.(*parser).pos = tokenpos(mtaillex)
		}
	case 129:
		mtailDollar = mtailS[mtailpt-0 : mtailpt+1]
//line parser.y:748
		{
			mtaillex.(*parser).inRegex()
		}
	}
	goto mtailstack /* stack new state and value */
}
