// Code generated by goyacc -v y.output -o parser.go -p mtail parser.y. DO NOT EDIT.

//line parser.y:5
/* #nosec G104 generated code, errors reported do not make sense */
package parser

import __yyfmt__ "fmt"

//line parser.y:6

import (
	"time"

	"github.com/golang/glog"
	"github.com/jaqx0r/mtail/internal/metrics"
	"github.com/jaqx0r/mtail/internal/runtime/compiler/ast"
	"github.com/jaqx0r/mtail/internal/runtime/compiler/position"
)

//line parser.y:19
type mtailSymType struct {
	yys       int
	intVal    int64
	floatVal  float64
	floats    []float64
	op        int
	text      string
	texts     []string
	flag      bool
	n         ast.Node
	kind      metrics.Kind
	duration  time.Duration
	logFilter *ast.LogFilter // Add this field for *ast.LogFilter
}

const INVALID = 57346
const COUNTER = 57347
const GAUGE = 57348
const TIMER = 57349
const TEXT = 57350
const HISTOGRAM = 57351
const AFTER = 57352
const AS = 57353
const BEGIN = 57354
const BY = 57355
const CONST = 57356
const HIDDEN = 57357
const DEF = 57358
const DEL = 57359
const NEXT = 57360
const OTHERWISE = 57361
const ELSE = 57362
const STOP = 57363
const BUCKETS = 57364
const LIMIT = 57365
const BUILTIN = 57366
const REGEX = 57367
const STRING = 57368
const CAPREF = 57369
const CAPREF_NAMED = 57370
const ID = 57371
const DECO = 57372
const INTLITERAL = 57373
const FLOATLITERAL = 57374
const DURATIONLITERAL = 57375
const INC = 57376
const DEC = 57377
const DIV = 57378
const MOD = 57379
const MUL = 57380
const MINUS = 57381
const PLUS = 57382
const POW = 57383
const SHL = 57384
const SHR = 57385
const LT = 57386
const GT = 57387
const LE = 57388
const GE = 57389
const EQ = 57390
const NE = 57391
const BITAND = 57392
const XOR = 57393
const BITOR = 57394
const NOT = 57395
const AND = 57396
const OR = 57397
const ADD_ASSIGN = 57398
const ASSIGN = 57399
const MATCH = 57400
const NOT_MATCH = 57401
const LCURLY = 57402
const RCURLY = 57403
const LPAREN = 57404
const RPAREN = 57405
const LSQUARE = 57406
const RSQUARE = 57407
const COMMA = 57408
const NL = 57409
const LOGFILTER = 57410

var mtailToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"INVALID",
	"COUNTER",
	"GAUGE",
	"TIMER",
	"TEXT",
	"HISTOGRAM",
	"AFTER",
	"AS",
	"BEGIN",
	"BY",
	"CONST",
	"HIDDEN",
	"DEF",
	"DEL",
	"NEXT",
	"OTHERWISE",
	"ELSE",
	"STOP",
	"BUCKETS",
	"LIMIT",
	"BUILTIN",
	"REGEX",
	"STRING",
	"CAPREF",
	"CAPREF_NAMED",
	"ID",
	"DECO",
	"INTLITERAL",
	"FLOATLITERAL",
	"DURATIONLITERAL",
	"INC",
	"DEC",
	"DIV",
	"MOD",
	"MUL",
	"MINUS",
	"PLUS",
	"POW",
	"SHL",
	"SHR",
	"LT",
	"GT",
	"LE",
	"GE",
	"EQ",
	"NE",
	"BITAND",
	"XOR",
	"BITOR",
	"NOT",
	"AND",
	"OR",
	"ADD_ASSIGN",
	"ASSIGN",
	"MATCH",
	"NOT_MATCH",
	"LCURLY",
	"RCURLY",
	"LPAREN",
	"RPAREN",
	"LSQUARE",
	"RSQUARE",
	"COMMA",
	"NL",
	"LOGFILTER",
}

var mtailStatenames = [...]string{}

const mtailEofCode = 1
const mtailErrCode = 2
const mtailInitialStackSize = 16

//line parser.y:826

// tokenpos returns the position of the current token.
func tokenpos(mtaillex mtailLexer) position.Position {
	return mtaillex.(*parser).t.Pos
}

// markedpos returns the position recorded from the most recent mark_pos
// production.
func markedpos(mtaillex mtailLexer) position.Position {
	return mtaillex.(*parser).pos
}

// positionFromMark returns a position spanning from the last mark to the current position.
func positionFromMark(mtaillex mtailLexer) position.Position {
	tp := tokenpos(mtaillex)
	mp := markedpos(mtaillex)
	return *position.Merge(&mp, &tp)
}

//line yacctab:1
var mtailExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 1,
	5, 110,
	6, 110,
	7, 110,
	8, 110,
	9, 110,
	-2, 141,
	-1, 26,
	67, 32,
	-2, 85,
	-1, 119,
	5, 110,
	6, 110,
	7, 110,
	8, 110,
	9, 110,
	-2, 141,
}

const mtailPrivate = 57344

const mtailLast = 287

var mtailAct = [...]uint8{
	102, 54, 117, 18, 199, 144, 48, 143, 101, 105,
	47, 29, 32, 46, 34, 36, 33, 31, 53, 118,
	195, 49, 23, 190, 189, 190, 209, 146, 99, 30,
	22, 26, 64, 208, 120, 72, 73, 103, 15, 123,
	51, 2, 145, 75, 148, 24, 14, 98, 12, 27,
	194, 50, 11, 75, 100, 13, 89, 90, 87, 86,
	42, 40, 41, 35, 81, 44, 45, 72, 73, 57,
	42, 40, 41, 35, 132, 44, 45, 133, 134, 135,
	100, 72, 73, 136, 137, 138, 104, 37, 196, 139,
	140, 141, 127, 119, 142, 156, 43, 37, 83, 85,
	84, 19, 16, 80, 147, 60, 43, 159, 197, 149,
	122, 59, 150, 35, 126, 151, 107, 108, 155, 205,
	18, 111, 110, 60, 147, 125, 154, 56, 29, 32,
	55, 160, 153, 78, 79, 155, 201, 155, 155, 157,
	214, 213, 147, 175, 161, 179, 181, 22, 26, 174,
	29, 178, 180, 177, 182, 100, 188, 192, 186, 100,
	191, 193, 24, 59, 187, 176, 100, 100, 100, 185,
	200, 204, 203, 158, 163, 172, 173, 162, 15, 114,
	115, 113, 183, 184, 116, 121, 14, 131, 12, 27,
	130, 147, 11, 124, 1, 13, 206, 207, 78, 79,
	42, 40, 41, 35, 4, 44, 45, 202, 155, 166,
	200, 77, 88, 212, 76, 112, 211, 109, 42, 40,
	41, 35, 210, 44, 45, 82, 106, 37, 42, 40,
	41, 35, 91, 44, 45, 21, 43, 71, 74, 52,
	198, 19, 16, 164, 165, 37, 167, 92, 93, 94,
	95, 96, 97, 65, 43, 61, 63, 39, 58, 169,
	129, 168, 10, 59, 43, 9, 8, 128, 7, 62,
	170, 171, 152, 28, 38, 60, 66, 67, 68, 69,
	70, 25, 20, 6, 17, 5, 3,
}

var mtailPact = [...]int16{
	-1000, -1000, 174, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 84, -1000, -20, -1000, 101, -20, 239, -1000,
	-35, 271, 27, 13, 27, -1000, 99, -1000, 63, 24,
	48, -1000, 2, -2, -1000, -1000, 203, 192, -27, -1000,
	-1000, -1000, -1000, 192, -1000, -1000, 74, 82, 143, -48,
	-1000, -1000, -32, -1000, -1000, -1000, -1000, 165, -20, -23,
	-1000, 96, -20, 202, -1000, 161, -1000, -1000, -1000, -1000,
	-1000, -48, -1000, -1000, -48, -48, -48, -1000, -1000, -1000,
	-48, -48, -48, -1000, -1000, -1000, -48, -48, -48, -1000,
	-1000, -48, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 99,
	-1000, -1000, 139, 192, -19, -1000, -48, -1000, -1000, -48,
	-1000, -1000, -48, -1000, -1000, -1000, -1000, 84, -1000, 34,
	101, -20, -1000, 44, 119, -20, -1000, 164, 248, -1000,
	-1000, -1000, 192, 192, 84, 192, 84, 84, 192, 192,
	192, 202, 192, -41, -1000, 27, -1000, 87, -1000, 192,
	192, 192, 10, -1000, -1000, 69, -1000, -1000, -1000, -1000,
	-43, 52, -1000, 75, -1000, -1000, -1000, -1000, 101, 110,
	140, 88, 27, 27, -1000, -1000, 48, -1000, -1000, -1000,
	-1000, -1000, 203, 27, 27, -1000, -1000, 3, 74, -1000,
	192, 82, 143, -1000, -48, -1000, -1000, -1000, -33, -1000,
	-1000, -1000, -40, -1000, -1000, -1000, -1000, 84, 101, 109,
	-1000, -1000, -1000, -1000, -1000,
}

var mtailPgo = [...]int16{
	0, 41, 286, 7, 51, 285, 284, 283, 282, 16,
	6, 10, 28, 9, 281, 15, 13, 29, 42, 274,
	8, 273, 27, 272, 22, 268, 267, 266, 265, 14,
	17, 262, 260, 257, 5, 253, 246, 244, 1, 4,
	18, 243, 240, 239, 235, 232, 226, 225, 214, 217,
	215, 212, 211, 209, 207, 204, 194, 2, 0, 193,
}

var mtailR1 = [...]int8{
	0, 56, 1, 1, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 55, 43, 43, 40,
	5, 5, 5, 6, 6, 6, 6, 6, 7, 7,
	4, 8, 8, 14, 14, 18, 18, 18, 18, 48,
	48, 17, 17, 47, 47, 47, 15, 15, 45, 45,
	45, 45, 45, 45, 16, 16, 46, 46, 11, 11,
	49, 49, 30, 30, 30, 51, 51, 22, 23, 23,
	23, 23, 24, 24, 24, 24, 21, 21, 21, 10,
	10, 50, 50, 50, 50, 13, 13, 12, 12, 52,
	52, 9, 9, 9, 9, 9, 9, 9, 9, 19,
	19, 20, 33, 33, 3, 3, 34, 34, 29, 25,
	44, 44, 26, 26, 26, 26, 26, 32, 32, 35,
	35, 35, 35, 35, 41, 42, 42, 39, 37, 36,
	53, 54, 54, 54, 54, 27, 28, 31, 31, 38,
	38, 58, 59, 57, 57,
}

var mtailR2 = [...]int8{
	0, 1, 0, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 4, 1, 2, 1, 2, 1, 3, 1,
	4, 2, 3, 1, 4, 1, 4, 1, 1, 2,
	3, 1, 1, 4, 4, 1, 1, 4, 4, 1,
	1, 1, 4, 1, 1, 1, 1, 4, 1, 1,
	1, 1, 1, 1, 1, 4, 1, 1, 1, 4,
	1, 1, 4, 4, 4, 1, 1, 1, 1, 1,
	4, 4, 4, 4, 4, 4, 1, 4, 4, 1,
	4, 1, 1, 1, 1, 1, 2, 1, 2, 1,
	1, 1, 1, 1, 1, 1, 3, 1, 1, 1,
	4, 1, 4, 5, 1, 3, 1, 1, 5, 3,
	0, 1, 2, 2, 2, 2, 1, 1, 1, 1,
	1, 1, 1, 1, 2, 1, 3, 1, 2, 2,
	2, 1, 1, 3, 3, 4, 3, 5, 3, 1,
	1, 0, 0, 0, 1,
}

var mtailChk = [...]int16{
	-1000, -56, -1, -2, -55, -5, -7, -25, -27, -28,
	-31, 18, 14, 21, 12, 4, 68, -6, -58, 67,
	-8, -44, -22, -24, -18, -14, -12, 15, -21, -20,
	-17, -30, -13, -9, -29, 29, -15, 53, -19, -33,
	27, 28, 26, 62, 31, 32, -16, -11, -10, -20,
	-4, 60, -43, -40, -38, 29, 26, -4, 19, 24,
	36, 16, 30, 17, 67, -35, 5, 6, 7, 8,
	9, -48, 54, 55, -48, 40, -48, -52, 34, 35,
	40, 40, -47, 50, 52, 51, 57, 56, -51, 58,
	59, -45, 44, 45, 46, 47, 48, 49, -13, -12,
	-9, -20, -58, 64, -18, -13, -46, 42, 43, -49,
	40, 39, -50, 38, 36, 37, 41, -57, 67, -1,
	66, 20, -4, 62, -59, 29, -4, -12, -26, -32,
	29, 26, -57, -57, -57, -57, -57, -57, -57, -57,
	-57, -57, -57, -3, -34, -18, -22, -58, 63, -57,
	-57, -57, -23, -29, -20, -58, 61, -40, -4, 63,
	-3, 25, -4, 10, -41, -37, -53, -36, 13, 11,
	22, 23, -18, -18, -29, -20, -17, -30, -29, -20,
	-29, -20, -15, -18, -18, -22, -9, -24, -16, 65,
	66, -11, -10, -13, 40, 63, 36, 33, -42, -39,
	-38, 26, -54, 32, 31, 31, -34, -57, 66, 66,
	-29, -20, -39, 32, 31,
}

var mtailDef = [...]int16{
	2, -2, -2, 3, 4, 5, 6, 7, 8, 9,
	10, 11, 0, 13, 0, 15, 0, 0, 0, 28,
	0, 0, 23, 25, 27, 31, -2, 111, 67, 99,
	35, 36, 79, 87, 76, 101, 41, 141, 91, 92,
	93, 94, 95, 141, 97, 98, 46, 54, 58, 143,
	14, 2, 16, 17, 19, 139, 140, 21, 0, 0,
	142, 0, 0, 141, 29, 0, 119, 120, 121, 122,
	123, 143, 39, 40, 143, 143, 143, 88, 89, 90,
	143, 143, 143, 43, 44, 45, 143, 143, 143, 65,
	66, 143, 48, 49, 50, 51, 52, 53, 86, 85,
	87, 99, 0, 141, 0, 79, 143, 56, 57, 143,
	60, 61, 143, 81, 82, 83, 84, 141, 144, -2,
	0, 0, 22, 141, 0, 0, 136, 138, 109, 116,
	117, 118, 141, 141, 141, 141, 141, 141, 141, 141,
	141, 141, 141, 0, 104, 106, 107, 0, 96, 141,
	141, 141, 12, 68, 69, 0, 30, 18, 20, 102,
	0, 0, 135, 0, 112, 113, 114, 115, 0, 0,
	0, 0, 24, 26, 74, 75, 37, 38, 77, 78,
	72, 73, 42, 33, 34, 62, 63, 64, 47, 100,
	141, 55, 59, 80, 143, 103, 108, 137, 124, 125,
	127, 128, 130, 131, 132, 129, 105, 141, 0, 0,
	70, 71, 126, 133, 134,
}

var mtailTok1 = [...]int8{
	1,
}

var mtailTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68,
}

var mtailTok3 = [...]int8{
	0,
}

var mtailErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{
	{124, 4, "unexpected end of file, expecting '/' to end regex"},
	{18, 1, "unexpected end of file, expecting '}' to end block"},
	{18, 1, "unexpected end of file, expecting '}' to end block"},
	{18, 1, "unexpected end of file, expecting '}' to end block"},
	{17, 64, "unexpected indexing of an expression"},
	{17, 67, "statement with no effect, missing an assignment, `+' concatenation, or `{}' block?"},
}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	mtailDebug        = 0
	mtailErrorVerbose = false
)

type mtailLexer interface {
	Lex(lval *mtailSymType) int
	Error(s string)
}

type mtailParser interface {
	Parse(mtailLexer) int
	Lookahead() int
}

type mtailParserImpl struct {
	lval  mtailSymType
	stack [mtailInitialStackSize]mtailSymType
	char  int
}

func (p *mtailParserImpl) Lookahead() int {
	return p.char
}

func mtailNewParser() mtailParser {
	return &mtailParserImpl{}
}

const mtailFlag = -1000

func mtailTokname(c int) string {
	if c >= 1 && c-1 < len(mtailToknames) {
		if mtailToknames[c-1] != "" {
			return mtailToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func mtailStatname(s int) string {
	if s >= 0 && s < len(mtailStatenames) {
		if mtailStatenames[s] != "" {
			return mtailStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func mtailErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !mtailErrorVerbose {
		return "syntax error"
	}

	for _, e := range mtailErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + mtailTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(mtailPact[state])
	for tok := TOKSTART; tok-1 < len(mtailToknames); tok++ {
		if n := base + tok; n >= 0 && n < mtailLast && int(mtailChk[int(mtailAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if mtailDef[state] == -2 {
		i := 0
		for mtailExca[i] != -1 || int(mtailExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; mtailExca[i] >= 0; i += 2 {
			tok := int(mtailExca[i])
			if tok < TOKSTART || mtailExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if mtailExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += mtailTokname(tok)
	}
	return res
}

func mtaillex1(lex mtailLexer, lval *mtailSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(mtailTok1[0])
		goto out
	}
	if char < len(mtailTok1) {
		token = int(mtailTok1[char])
		goto out
	}
	if char >= mtailPrivate {
		if char < mtailPrivate+len(mtailTok2) {
			token = int(mtailTok2[char-mtailPrivate])
			goto out
		}
	}
	for i := 0; i < len(mtailTok3); i += 2 {
		token = int(mtailTok3[i+0])
		if token == char {
			token = int(mtailTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(mtailTok2[1]) /* unknown char */
	}
	if mtailDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", mtailTokname(token), uint(char))
	}
	return char, token
}

func mtailParse(mtaillex mtailLexer) int {
	return mtailNewParser().Parse(mtaillex)
}

func (mtailrcvr *mtailParserImpl) Parse(mtaillex mtailLexer) int {
	var mtailn int
	var mtailVAL mtailSymType
	var mtailDollar []mtailSymType
	_ = mtailDollar // silence set and not used
	mtailS := mtailrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	mtailstate := 0
	mtailrcvr.char = -1
	mtailtoken := -1 // mtailrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		mtailstate = -1
		mtailrcvr.char = -1
		mtailtoken = -1
	}()
	mtailp := -1
	goto mtailstack

ret0:
	return 0

ret1:
	return 1

mtailstack:
	/* put a state and value onto the stack */
	if mtailDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", mtailTokname(mtailtoken), mtailStatname(mtailstate))
	}

	mtailp++
	if mtailp >= len(mtailS) {
		nyys := make([]mtailSymType, len(mtailS)*2)
		copy(nyys, mtailS)
		mtailS = nyys
	}
	mtailS[mtailp] = mtailVAL
	mtailS[mtailp].yys = mtailstate

mtailnewstate:
	mtailn = int(mtailPact[mtailstate])
	if mtailn <= mtailFlag {
		goto mtaildefault /* simple state */
	}
	if mtailrcvr.char < 0 {
		mtailrcvr.char, mtailtoken = mtaillex1(mtaillex, &mtailrcvr.lval)
	}
	mtailn += mtailtoken
	if mtailn < 0 || mtailn >= mtailLast {
		goto mtaildefault
	}
	mtailn = int(mtailAct[mtailn])
	if int(mtailChk[mtailn]) == mtailtoken { /* valid shift */
		mtailrcvr.char = -1
		mtailtoken = -1
		mtailVAL = mtailrcvr.lval
		mtailstate = mtailn
		if Errflag > 0 {
			Errflag--
		}
		goto mtailstack
	}

mtaildefault:
	/* default state action */
	mtailn = int(mtailDef[mtailstate])
	if mtailn == -2 {
		if mtailrcvr.char < 0 {
			mtailrcvr.char, mtailtoken = mtaillex1(mtaillex, &mtailrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if mtailExca[xi+0] == -1 && int(mtailExca[xi+1]) == mtailstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			mtailn = int(mtailExca[xi+0])
			if mtailn < 0 || mtailn == mtailtoken {
				break
			}
		}
		mtailn = int(mtailExca[xi+1])
		if mtailn < 0 {
			goto ret0
		}
	}
	if mtailn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			mtaillex.Error(mtailErrorMessage(mtailstate, mtailtoken))
			Nerrs++
			if mtailDebug >= 1 {
				__yyfmt__.Printf("%s", mtailStatname(mtailstate))
				__yyfmt__.Printf(" saw %s\n", mtailTokname(mtailtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for mtailp >= 0 {
				mtailn = int(mtailPact[mtailS[mtailp].yys]) + mtailErrCode
				if mtailn >= 0 && mtailn < mtailLast {
					mtailstate = int(mtailAct[mtailn]) /* simulate a shift of "error" */
					if int(mtailChk[mtailstate]) == mtailErrCode {
						goto mtailstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if mtailDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", mtailS[mtailp].yys)
				}
				mtailp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if mtailDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", mtailTokname(mtailtoken))
			}
			if mtailtoken == mtailEofCode {
				goto ret1
			}
			mtailrcvr.char = -1
			mtailtoken = -1
			goto mtailnewstate /* try again in the same state */
		}
	}

	/* reduction by production mtailn */
	if mtailDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", mtailn, mtailStatname(mtailstate))
	}

	mtailnt := mtailn
	mtailpt := mtailp
	_ = mtailpt // guard against "declared and not used"

	mtailp -= int(mtailR2[mtailn])
	// mtailp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if mtailp+1 >= len(mtailS) {
		nyys := make([]mtailSymType, len(mtailS)*2)
		copy(nyys, mtailS)
		mtailS = nyys
	}
	mtailVAL = mtailS[mtailp+1]

	/* consult goto table to find next state */
	mtailn = int(mtailR1[mtailn])
	mtailg := int(mtailPgo[mtailn])
	mtailj := mtailg + mtailS[mtailp].yys + 1

	if mtailj >= mtailLast {
		mtailstate = int(mtailAct[mtailg])
	} else {
		mtailstate = int(mtailAct[mtailj])
		if int(mtailChk[mtailstate]) != -mtailn {
			mtailstate = int(mtailAct[mtailg])
		}
	}
	// dummy call; replaced with literal code
	switch mtailnt {

	case 1:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:96
		{
			mtaillex.(*parser).root = mtailDollar[1].n
		}
	case 2:
		mtailDollar = mtailS[mtailpt-0 : mtailpt+1]
//line parser.y:104
		{
			mtailVAL.n = &ast.StmtList{}
		}
	case 3:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:108
		{
			mtailVAL.n = mtailDollar[1].n
			if mtailDollar[2].n != nil {
				mtailVAL.n.(*ast.StmtList).Children = append(mtailVAL.n.(*ast.StmtList).Children, mtailDollar[2].n)
			}
		}
	case 4:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:119
		{
			mtailVAL.n = mtailDollar[1].logFilter
		}
	case 5:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:121
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 6:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:123
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 7:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:125
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 8:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:127
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 9:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:129
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 10:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:131
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 11:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:133
		{
			mtailVAL.n = &ast.NextStmt{tokenpos(mtaillex)}
		}
	case 12:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:137
		{
			mtailVAL.n = &ast.PatternFragment{ID: mtailDollar[2].n, Expr: mtailDollar[4].n}
		}
	case 13:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:141
		{
			mtailVAL.n = &ast.StopStmt{tokenpos(mtaillex)}
		}
	case 14:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:145
		{
			mtailVAL.n = &ast.BeginStmt{P: tokenpos(mtaillex), Block: mtailDollar[2].n}
		}
	case 15:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:149
		{
			mtailVAL.n = &ast.Error{tokenpos(mtaillex), mtailDollar[1].text}
		}
	case 16:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:156
		{
			mtailVAL.logFilter = &ast.LogFilter{
				P:       tokenpos(mtaillex),
				Filters: mtailDollar[2].texts, // $2 is the list of strings (type []string)
			}
		}
	case 17:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:166
		{
			mtailVAL.texts = make([]string, 0)
			mtailVAL.texts = append(mtailVAL.texts, mtailDollar[1].text)
		}
	case 18:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:171
		{
			mtailVAL.texts = mtailDollar[1].texts
			mtailVAL.texts = append(mtailVAL.texts, mtailDollar[3].text)
		}
	case 19:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:179
		{
			mtailVAL.text = mtailDollar[1].text
		}
	case 20:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:185
		{
			mtailVAL.n = &ast.CondStmt{mtailDollar[1].n, mtailDollar[2].n, mtailDollar[4].n, nil}
		}
	case 21:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:189
		{
			if mtailDollar[1].n != nil {
				mtailVAL.n = &ast.CondStmt{mtailDollar[1].n, mtailDollar[2].n, nil, nil}
			} else {
				mtailVAL.n = mtailDollar[2].n
			}
		}
	case 22:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:197
		{
			o := &ast.OtherwiseStmt{positionFromMark(mtaillex)}
			mtailVAL.n = &ast.CondStmt{o, mtailDollar[3].n, nil, nil}
		}
	case 23:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:205
		{
			mtailVAL.n = &ast.UnaryExpr{P: tokenpos(mtaillex), Expr: mtailDollar[1].n, Op: MATCH}
		}
	case 24:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:209
		{
			mtailVAL.n = &ast.BinaryExpr{
				LHS: &ast.UnaryExpr{P: tokenpos(mtaillex), Expr: mtailDollar[1].n, Op: MATCH},
				RHS: mtailDollar[4].n,
				Op:  mtailDollar[2].op,
			}
		}
	case 25:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:217
		{
			mtailVAL.n = &ast.UnaryExpr{P: tokenpos(mtaillex), Expr: &ast.PatternExpr{Expr: mtailDollar[1].n}, Op: MATCH}
		}
	case 26:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:221
		{
			mtailVAL.n = &ast.BinaryExpr{
				LHS: &ast.UnaryExpr{P: tokenpos(mtaillex), Expr: &ast.PatternExpr{Expr: mtailDollar[1].n}, Op: MATCH},
				RHS: mtailDollar[4].n,
				Op:  mtailDollar[2].op,
			}
		}
	case 27:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:229
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 28:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:235
		{
			mtailVAL.n = nil
		}
	case 29:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:237
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 30:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:243
		{
			mtailVAL.n = mtailDollar[2].n
		}
	case 31:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:251
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 32:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:253
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 33:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:259
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 34:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:263
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 35:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:271
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 36:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:273
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 37:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:275
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 38:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:279
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 39:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:286
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 40:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:288
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 41:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:294
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 42:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:296
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 43:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:303
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 44:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:305
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 45:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:307
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 46:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:313
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 47:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:315
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 48:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:322
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 49:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:324
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 50:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:326
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 51:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:328
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 52:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:330
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 53:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:332
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 54:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:338
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 55:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:340
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 56:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:347
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 57:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:349
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 58:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:355
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 59:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:357
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 60:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:364
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 61:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:366
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 62:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:372
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 63:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:376
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 64:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:380
		{
			mtailVAL.n = &ast.BinaryExpr{
				LHS: mtailDollar[1].n,
				RHS: &ast.PatternExpr{Expr: mtailDollar[4].n},
				Op:  mtailDollar[2].op,
			}
		}
	case 65:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:391
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 66:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:393
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 67:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:400
		{
			mtailVAL.n = &ast.PatternExpr{Expr: mtailDollar[1].n}
		}
	case 68:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:408
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 69:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:410
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 70:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:412
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: PLUS}
		}
	case 71:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:416
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: PLUS}
		}
	case 72:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:424
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: PLUS}
		}
	case 73:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:428
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: PLUS}
		}
	case 74:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:432
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: PLUS}
		}
	case 75:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:436
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: PLUS}
		}
	case 76:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:444
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 77:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:446
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: PLUS}
		}
	case 78:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:450
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: PLUS}
		}
	case 79:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:458
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 80:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:460
		{
			mtailVAL.n = &ast.BinaryExpr{LHS: mtailDollar[1].n, RHS: mtailDollar[4].n, Op: mtailDollar[2].op}
		}
	case 81:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:467
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 82:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:469
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 83:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:471
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 84:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:473
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 85:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:479
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 86:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:481
		{
			mtailVAL.n = &ast.UnaryExpr{P: tokenpos(mtaillex), Expr: mtailDollar[2].n, Op: mtailDollar[1].op}
		}
	case 87:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:489
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 88:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:491
		{
			mtailVAL.n = &ast.UnaryExpr{P: tokenpos(mtaillex), Expr: mtailDollar[1].n, Op: mtailDollar[2].op}
		}
	case 89:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:498
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 90:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:500
		{
			mtailVAL.op = mtailDollar[1].op
		}
	case 91:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:506
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 92:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:508
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 93:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:510
		{
			mtailVAL.n = &ast.CaprefTerm{tokenpos(mtaillex), mtailDollar[1].text, false, nil}
		}
	case 94:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:514
		{
			mtailVAL.n = &ast.CaprefTerm{tokenpos(mtaillex), mtailDollar[1].text, true, nil}
		}
	case 95:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:518
		{
			mtailVAL.n = &ast.StringLit{tokenpos(mtaillex), mtailDollar[1].text}
		}
	case 96:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:522
		{
			mtailVAL.n = mtailDollar[2].n
		}
	case 97:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:526
		{
			mtailVAL.n = &ast.IntLit{tokenpos(mtaillex), mtailDollar[1].intVal}
		}
	case 98:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:530
		{
			mtailVAL.n = &ast.FloatLit{tokenpos(mtaillex), mtailDollar[1].floatVal}
		}
	case 99:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:538
		{
			// Build an empty IndexedExpr so that the recursive rule below doesn't need to handle the alternative.
			mtailVAL.n = &ast.IndexedExpr{LHS: mtailDollar[1].n, Index: &ast.ExprList{}}
		}
	case 100:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:543
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.IndexedExpr).Index.(*ast.ExprList).Children = append(
				mtailVAL.n.(*ast.IndexedExpr).Index.(*ast.ExprList).Children,
				mtailDollar[3].n.(*ast.ExprList).Children...)
		}
	case 101:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:554
		{
			mtailVAL.n = &ast.IDTerm{tokenpos(mtaillex), mtailDollar[1].text, nil, false}
		}
	case 102:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:562
		{
			mtailVAL.n = &ast.BuiltinExpr{P: positionFromMark(mtaillex), Name: mtailDollar[2].text, Args: nil}
		}
	case 103:
		mtailDollar = mtailS[mtailpt-5 : mtailpt+1]
//line parser.y:566
		{
			mtailVAL.n = &ast.BuiltinExpr{P: positionFromMark(mtaillex), Name: mtailDollar[2].text, Args: mtailDollar[4].n}
		}
	case 104:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:575
		{
			mtailVAL.n = &ast.ExprList{}
			mtailVAL.n.(*ast.ExprList).Children = append(mtailVAL.n.(*ast.ExprList).Children, mtailDollar[1].n)
		}
	case 105:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:580
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.ExprList).Children = append(mtailVAL.n.(*ast.ExprList).Children, mtailDollar[3].n)
		}
	case 106:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:588
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 107:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:590
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 108:
		mtailDollar = mtailS[mtailpt-5 : mtailpt+1]
//line parser.y:596
		{
			mtailVAL.n = &ast.PatternLit{P: positionFromMark(mtaillex), Pattern: mtailDollar[4].text}
		}
	case 109:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:604
		{
			mtailVAL.n = mtailDollar[3].n
			d := mtailVAL.n.(*ast.VarDecl)
			d.Kind = mtailDollar[2].kind
			d.Hidden = mtailDollar[1].flag
		}
	case 110:
		mtailDollar = mtailS[mtailpt-0 : mtailpt+1]
//line parser.y:615
		{
			mtailVAL.flag = false
		}
	case 111:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:619
		{
			mtailVAL.flag = true
		}
	case 112:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:627
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.VarDecl).Keys = mtailDollar[2].texts
		}
	case 113:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:632
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.VarDecl).ExportedName = mtailDollar[2].text
		}
	case 114:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:637
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.VarDecl).Buckets = mtailDollar[2].floats
		}
	case 115:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:642
		{
			mtailVAL.n = mtailDollar[1].n
			mtailVAL.n.(*ast.VarDecl).Limit = mtailDollar[2].intVal
		}
	case 116:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:647
		{
			mtailVAL.n = mtailDollar[1].n
		}
	case 117:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:655
		{
			mtailVAL.n = &ast.VarDecl{P: tokenpos(mtaillex), Name: mtailDollar[1].text}
		}
	case 118:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:659
		{
			mtailVAL.n = &ast.VarDecl{P: tokenpos(mtaillex), Name: mtailDollar[1].text}
		}
	case 119:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:667
		{
			mtailVAL.kind = metrics.Counter
		}
	case 120:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:671
		{
			mtailVAL.kind = metrics.Gauge
		}
	case 121:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:675
		{
			mtailVAL.kind = metrics.Timer
		}
	case 122:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:679
		{
			mtailVAL.kind = metrics.Text
		}
	case 123:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:683
		{
			mtailVAL.kind = metrics.Histogram
		}
	case 124:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:691
		{
			mtailVAL.texts = mtailDollar[2].texts
		}
	case 125:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:698
		{
			mtailVAL.texts = make([]string, 0)
			mtailVAL.texts = append(mtailVAL.texts, mtailDollar[1].text)
		}
	case 126:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:703
		{
			mtailVAL.texts = mtailDollar[1].texts
			mtailVAL.texts = append(mtailVAL.texts, mtailDollar[3].text)
		}
	case 127:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:711
		{
			mtailVAL.text = mtailDollar[1].text
		}
	case 128:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:717
		{
			mtailVAL.text = mtailDollar[2].text
		}
	case 129:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:724
		{
			mtailVAL.intVal = mtailDollar[2].intVal
		}
	case 130:
		mtailDollar = mtailS[mtailpt-2 : mtailpt+1]
//line parser.y:732
		{
			mtailVAL.floats = mtailDollar[2].floats
		}
	case 131:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:738
		{
			mtailVAL.floats = make([]float64, 0)
			mtailVAL.floats = append(mtailVAL.floats, mtailDollar[1].floatVal)
		}
	case 132:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:743
		{
			mtailVAL.floats = make([]float64, 0)
			mtailVAL.floats = append(mtailVAL.floats, float64(mtailDollar[1].intVal))
		}
	case 133:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:748
		{
			mtailVAL.floats = mtailDollar[1].floats
			mtailVAL.floats = append(mtailVAL.floats, mtailDollar[3].floatVal)
		}
	case 134:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:753
		{
			mtailVAL.floats = mtailDollar[1].floats
			mtailVAL.floats = append(mtailVAL.floats, float64(mtailDollar[3].intVal))
		}
	case 135:
		mtailDollar = mtailS[mtailpt-4 : mtailpt+1]
//line parser.y:761
		{
			mtailVAL.n = &ast.DecoDecl{P: markedpos(mtaillex), Name: mtailDollar[3].text, Block: mtailDollar[4].n}
		}
	case 136:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:769
		{
			mtailVAL.n = &ast.DecoStmt{markedpos(mtaillex), mtailDollar[2].text, mtailDollar[3].n, nil, nil}
		}
	case 137:
		mtailDollar = mtailS[mtailpt-5 : mtailpt+1]
//line parser.y:777
		{
			mtailVAL.n = &ast.DelStmt{P: positionFromMark(mtaillex), N: mtailDollar[3].n, Expiry: mtailDollar[5].duration}
		}
	case 138:
		mtailDollar = mtailS[mtailpt-3 : mtailpt+1]
//line parser.y:781
		{
			mtailVAL.n = &ast.DelStmt{P: positionFromMark(mtaillex), N: mtailDollar[3].n}
		}
	case 139:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:788
		{
			mtailVAL.text = mtailDollar[1].text
		}
	case 140:
		mtailDollar = mtailS[mtailpt-1 : mtailpt+1]
//line parser.y:792
		{
			mtailVAL.text = mtailDollar[1].text
		}
	case 141:
		mtailDollar = mtailS[mtailpt-0 : mtailpt+1]
//line parser.y:802
		{
			glog.V(2).Infof("position marked at %v", tokenpos(mtaillex))
			mtaillex.(*parser).pos = tokenpos(mtaillex)
		}
	case 142:
		mtailDollar = mtailS[mtailpt-0 : mtailpt+1]
//line parser.y:812
		{
			mtaillex.(*parser).inRegex()
		}
	}
	goto mtailstack /* stack new state and value */
}
