name: Automatic pull request approvals
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  check_suite:
    types:
      - completed
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.draft == false && (
        github.event.action == 'opened' ||
        github.event.action == 'reopened' ||
        github.event.action == 'synchronize'
      ) && (
        github.actor == 'dependabot[bot]' ||
        github.actor == 'jaqx0r'
      )
    steps:
      - uses: "actions/github-script@v6.3.0"
        with:
          github-token: ${{ github.token }}
          script: |
            await github.pulls.createReview({
              event: "APPROVE",
              owner: context.repo.owner,
              pull_number: context.payload.pull_request.number,
              repo: context.repo.repo,
            })
